### ISSUE TITLE
Hey dude. whatever you're doing, its really frustrating

### ISSUE THREAD

**Issue by Lindsayanng** [wsergio/ophmisu#1]
http://cl.ly/image/1a1D44053S1W

**Comment by wsergio** [comment]
Oh, dang. Thanks for telling me. 
I killed it. Sorry for that!

**Comment by Lindsayanng** [comment]
No worries. Figured you would like to know. Thanks

**Comment by wsergio** [comment]
It seems my IRC client was trying to quickly join a few big channels (w/ >1000 users), without any delays.
